# Generated by Django 2.0 on 2018-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('longtitude', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('copen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid', models.CharField(blank=True, max_length=50, null=True)),
                ('ask', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('avgvolume', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('EPS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('day_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('week_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('week_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
